#' Simulates head circumference data from an SEIR vector borne model
#'
#' Takes a list of necessary arguments to solve a system of ODEs that generates head circumferences of new born infants
#' @param allPars A list of parameter vectors. First vector should be an array of time points over which to solve the SEIR model. Second vector should be the vector of starting conditions. Third vector should be all of the parameters.
#' @return a matrix of simulated head circumferences over time.
#' @export
#' @useDynLib zikaProj
zika.sim <- function(allPars,headMeasurements=TRUE,buckets=NULL){
    ## Get length and time step for ODE solver
    y <- solveModel(allPars)
    y <- as.data.frame(y)
    y0s <- allPars[[2]]
    pars <- allPars[[3]]
    
    sampFreq <- pars["sampFreq"]
    sampPropn <- pars["sampPropn"]
    mu_I <- pars["mu_I"]
    sd_I <- pars["sd_I"]
    mu_N <- pars["mu_N"]
    sd_N <- pars["sd_N"]
    probMicro <- pars["probMicro"]
    baselineProb <- pars["baselineProb"]
    lifeExpectancy <- pars["L_H"]
 
    daysPerYear <- nrow(y)/max(y$times)
    birthsPerYear <- sum(y0s[4:6])/lifeExpectancy
    birthsPerDay <- ceiling(birthsPerYear/daysPerYear)
    if(headMeasurements){
        if(!is.null(buckets)){
            alphas_I<- calculate_alphas_buckets(as.matrix(unname(y[,c("times","I_F","S_F","E_F","R_F")])),probMicro,buckets)
        }
        else {
            alphas_I<- calculate_alphas(as.matrix(unname(y[,c("I_F","S_F","E_F","R_F")])),probMicro,sampFreq)
        }
        alphas_N <- 1 - alphas_I
    }
    else {
        if(!is.null(buckets)){
            alphas_I <- calculate_alphas_prob_buckets(as.matrix(unname(y[,c("times","I_F","S_F","E_F","R_F")])),probMicro, baselineProb, buckets)
        }
        else {
            alphas_I <- calculate_alphas_prob_sampfreq(as.matrix(unname(y[,c("I_F","S_F","E_F","R_F")])),probMicro, baselineProb, sampFreq)
        }
    }
    N <- sampPropn*birthsPerDay*sampFreq
    index <- 1
    all <- NULL
    while(index <= length(alphas_I)){
        if(!is.null(buckets)) N <- sampPropn*(birthsPerYear*(buckets[index,"end"]-buckets[index,"start"]))
        else N <- sampPropn*(birthsPerDay*sampFreq)

        if(headMeasurements){
            components <- sample(1:2,c(alphas_I[index],alphas_N[index]),size=N,replace=TRUE)
            mus <- c(mu_I,mu_N)
            sds <- c(sd_I,sd_N)
            
            distribution <- round(rnorm(n=N,mean=mus[components],sd=sds[components]),digits=1)
            all[[index]] <- distribution
        }
        else all[[index]] <- rbind(ceiling(alphas_I[index]*N), ceiling(N-(alphas_I[index]*N)))
        index <- index + 1
    }
    tmp <- as.matrix(rbind.fill(lapply(all,function(x) {as.data.frame(t(x))})))
    if(!headMeasurements | !is.null(buckets)) colnames(tmp) <- c("microCeph","births")
    return(tmp)
}

#' Solve ODE model
#'
#' Given a list of parameters as generated by \code{\link{setupListPars}}, solves the ODE model and returns a named data frame that can be passed to \code{\link{plot_dynamics}}
#' @param allPars the list of parameters needed for the ODE model
#' @return a data frame of the solved ODE model
#' @export
solveModel <- function(allPars){
    ## First set of pars is time parameters
    t_pars <- allPars[[1]]
    ## Run time of model
    time_length<- t_pars[1]
    ## Step size
    time_by <- t_pars[2]

    ## Second set of pars is starting population sizes
    y0s <- allPars[[2]]

    ## Third set of pars is model parameters
    pars <- allPars[[3]]

    ## Burn in and delayed epidemic start
    burnin <- pars["burnin"]
    epiStart <- pars["epiStart"]

    ## Temporarily remove initial seeding  for burn in period
    I0 <- y0s["I_A"]
    y0s[11] <- 0
    y0s[5] <- y0s["S_A"] + I0

    ## Package ODE pars
    pars <- pars[c("L_M","D_EM","L_H","D_C","D_F","D_EH","D_IH","b","p_HM","p_MH","constSeed")]

    ## Create time series for ode solver
    ts1 <- seq(0, burnin+epiStart,by=time_by)
    ts2 <- seq(epiStart, time_length,by=time_by)
    if(epiStart < time_by) epiStart <- time_by
    #ts2 <- ts2 - epiStart
    if(length(ts1) < 1 | length(ts2) < 1) return("Error")

    ## Solve ODEs from 0 to epiStart, via burnin
    y1 <- ode(y0s,ts1,func="derivs",parms=pars,dllname="zikaProj",initfunc="initmod",hmax=1e-4,nout=0)
    if(is.null(y1) || nrow(y1) < 0) return("Error")
    colnames(y1) <- c("times","S_M","E_M","I_M","S_C","S_A","S_F","E_C","E_A","E_F","I_C","I_A","I_F","R_C","R_A","R_F")
    ## Get final population sizes as start for next part
    ## If epidemic start was delayed, use end of burn in. If not, just use original starting values.
    y0s2 <- y1[nrow(y1),2:ncol(y1)]
    if(burnin > 0){
        if(!is.null(y1) && nrow(y1) > 1){
            y1 <- y1[y1[,"times"] >= burnin,]
        }
        else return("Error")
        if(epiStart > 0) y1[,"times"] <- y1[,"times"]- burnin
    }

    ## Restore I0 to positive value
    y0s2["I_A"] <- I0
    y0s2["S_A"] <- y0s2["S_A"] - I0

    y <- ode(y0s2,ts2,func="derivs",parms=pars,dllname="zikaProj",initfunc="initmod",hmax=1e-4,nout=0)
    if(is.null(y)) return("Error")
    
    if(epiStart > 0){
        y <- rbind(y1,y)
    }
    
    #y <- as.data.frame(y)
    colnames(y) <- c("times","S_M","E_M","I_M","S_C","S_A","S_F","E_C","E_A","E_F","I_C","I_A","I_F","R_C","R_A","R_F")
    return(y)
    
}


#' R0 calculation
#'
#' Calculates the R0 of the SEIR model given a vector of parameters and human/mosquito population sizes. R0 defined as number of expected human cases given introduction of 1 infected human into a totally naive population of humans and mosquitoes.
#' @param params Vector of parameters matching those returned by \code{\link{setupListPars}}
#' @param NH integer value for human population size
#' @param NM integer value for mosquito population size
#' @return A single value for R0
#' @export
#' @seealso \code{\link{b.calc}}
r0.calc <- function(params,NH,NM){
    muM <- 1/params["L_M"]
    sigmaM <- 1/params["D_EM"]

    muH <- 1/params["L_H"]
    gammaH <- 1/params["D_IH"]

    b <- params["b"]
    pHM <- params["p_HM"]
    pMH <- params["p_MH"]
    
        
    #'    first <- (b * pHM * NM)/((gammaH + muH)*NH)
    #'  second <- (sigmaM/(sigmaM+muM))*(b * pMH )/muM

    #' R0 <- first*second
    R0 <- (b^2*pHM*pMH*NM*sigmaM)/((sigmaM+muM)*muM*(gammaH+muH)*NH)
    return(unname(R0))
}

#' Bite rate calculation
#'
#' Calculates the bite rate needed to generate a given R0 value, assuming that all other parameters are fixed.
#' @param params Vector of parameters matching those returned by \code{\link{setupListPars}}
#' @param NH integer value for human population size
#' @param NM integer value for mosquito population size
#' @param R0 desired R0 value
#' @return A single value for bite rate
#' @export
#' @seealso \code{\link{r0.calc}}
b.calc <- function(params,NH,NM,R0){
    muM <- 1/params["L_M"]
    sigmaM <- 1/params["D_EM"]

    muH <- 1/params["L_H"]
    gammaH <- 1/params["D_IH"]

    b <- params["b"]
    pHM <- params["p_HM"]
    pMH <- params["p_MH"]
  
    b <- sqrt(((sigmaM+muM)*muM*(gammaH+muH)*NH)/((pHM * pMH * NM * sigmaM))*R0)
    return(unname(b))
    
}

#' Defaults ODE parameters
#'
#' Generates the default vector of parameters for the ODE model
#' @return vector of named parameter values
#' @export
#' @useDynLib zikaProj
setupParsODE <- function(){
    D_EM=10.5/360
    D_EH=4/360
    D_IH=5/360
    L_M=14/360
    L=73.6
    D_C=18
    D_F=3/12
    b=100
    p_MH=0.5
    p_HM=0.5
    offset <- 0
    
    pars <- c("L_M"=L_M,"D_EM"=D_EM,"L_H"=L,"D_C"=D_C,"D_F"=D_F,"D_EH"=D_EH,"D_IH"=D_IH,"b"=b,"p_HM"=p_HM,"p_MH"=p_MH,"constSeed"=offset)
    return(pars)
}

#' Default simulation parameters
#'
#' Generates the default vector of parameters for the simulation
#' @return vector of names parameter values
#' @export
#' @seealso \code{\link{setupParsODE}}
#' @useDynLib zikaProj
setupParsLong <- function(){
    pars <- setupParsODE()
    sampFreq <- 7
    sampPropn <- 0.9
    mu_I <- 28
    sd_I <- 2
    mu_N <- 35
    sd_N <- 2
    probMicro <- 1
    baseline <- 0.00002
    burnin <- 3
    epiStart <- 5
    pars <- c("sampFreq"=sampFreq,"sampPropn"=sampPropn,"mu_I"=mu_I,"sd_I"=sd_I,"mu_N"=mu_N,"sd_N"=sd_N,"probMicro"=probMicro,"baselineProb"=baseline,"burnin"=burnin,"epiStart"=epiStart,pars)
    return(pars)   
}

#' Default parameter list setup
#'
#' Sets up the default list of parameters and initial conditions to be used by \code{\link{zika.sim}}
#' @param duration Duration in years of the simulation. Defaults to 10 years
#' @return list of times, initial conditions, and ODE parameters
#' @export
#' @seealso \code{\link{setupParsLong}}
#' @useDynLib zikaProj
setupListPars <- function(duration=10, N_H = 1000000,N_M = 20000000){
    pars <- setupParsLong()
    D_C <- unname(pars["D_C"])
    L <- unname(pars["L_H"])
    S_M = 1*(N_M)
    E_M = 0
    I_M = 0
    S_F = 0.001*N_H
    S_C = D_C*N_H/(L+D_C)
    S_A = (1-0.001-D_C/(L+D_C))*N_H - 10
    E_C = 0
    E_A = 0
    E_F = 0
    I_C = 0
    I_A = 10
    I_F = 0
    R_C = 0
    R_A = 0
    R_F = 0

    y0 <- c("S_M"=S_M, "E_M"=E_M,"I_M"=I_M,"S_C"=S_C,"S_A"=S_A,"S_F"=S_F,"E_C"=E_C,"E_A"=E_A,"E_F"=E_F,"I_C"=I_C,"I_A"=I_A,"I_F"=I_F,"R_C"=R_C,"R_A"=R_A,"R_F"=R_F)
    ts <- c("dur"=duration,"step"=1/365)
    
    return(list(ts,y0,pars))
}





#' Obsolete - the R implementation of the ODE model
#'
#' Set of ODEs for the zika SEIR model to be used by deSolve
#' @param t the vector of times to be solved over
#' @param y the compartment states
#' @param pars the parameters used to solve the ODE model
#' @return set of derivatives at the given time point
#' @export
#' @useDynLib zikaProj
zika.ode <-function(t, y,pars){
  L_M <- pars[1]
  D_EM <- pars[2]
   
  L_H <- pars[3]
  D_C <- pars[4]
  D_F <- pars[5]
  D_EH <- pars[6]
  D_IH <- pars[7]
  B_H <- L_H - D_C
 
  b <- pars[8]
  P_HM <- pars[9]
  P_MH <- pars[10]
  
  t_seed <- pars[11]
  I0 <- pars[12]
  epsilon <- 0.0001
  seed <- 0
  offset <- 0
  
  if(t >= t_seed){
      offset <- pars[13]
      if(t < t_seed + epsilon){
          seed <- I0
      }
  }
  
  S_M <- y[1]
  E_M <- y[2]
  I_M <- y[3]
  S_C <- y[4]
  S_A <- y[5]
  S_F <- y[6]
  
  R_C <- y[13]
  R_A <- y[14]
  R_F <- y[15]
  
  N_H <- sum(y[4:15])
  N_M <- sum(y[1:3])
  
  lambda_M <- b*(N_M/N_H)*P_HM*(I_C + I_A + I_F + offset + seed)/N_H
  lambda_H <- b*(N_M/N_H)*P_MH*I_M/N_H
  
  dS_M <- N_M/L_M - S_M/L_M - lambda_M*S_M
  dE_M <- lambda_M*S_M - E_M/L_M - E_M/D_EM
  dI_M <- E_M/D_EM - I_M/L_M
  
  dS_C <- N_H/L_H - S_C/L_H - S_C/D_C - lambda_H*S_C
  dS_A <- S_C/D_C - S_A/L_H - S_A/B_H + S_F/D_F - lambda_H*S_A
  dS_F <- S_A/B_H - S_F/D_F - S_F/L_H - lambda_H*S_F
  
  dE_C <- lambda_H*S_C - E_C/L_H           - E_C/D_EH           - E_C/D_C
  dE_A <- lambda_H*S_A - E_A/L_H - E_A/B_H - E_A/D_EH + E_F/D_F + E_C/D_C
  dE_F <- lambda_H*S_F - E_F/L_H + E_A/B_H - E_F/D_EH - E_F/D_F
  
  dI_C <- E_C/D_EH - I_C/L_H - I_C/D_IH           - I_C/D_C
  dI_A <- E_A/D_EH - I_A/L_H - I_A/D_IH - I_A/B_H + I_C/D_C + I_F/D_F
  dI_F <- E_F/D_EH - I_F/L_H - I_F/D_IH + I_A/B_H           - I_F/D_F 
  
  dR_C <- I_C/D_IH - R_C/L_H - R_C/D_C
  dR_A <- I_A/D_IH + R_C/D_C - R_A/L_H - R_A/B_H + R_F/D_F
  dR_F <- I_F/D_IH + R_A/B_H - R_F/D_F - R_F/L_H
  
  dIf_A <- I_F/D_F
  df_B <- S_F/D_F + E_F/D_F + R_F/D_F + I_F/D_F
  dE <- E_C/D_EH + E_A/D_EH + E_F/D_EH
  
  return(list(c(dS_M,dE_M,dI_M,dS_C,dS_A,dS_F,dE_C,dE_A,dE_F,dI_C,dI_A,dI_F,dR_C,dR_A,dR_F,dIf_A,df_B,dE)))
}
