# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converts to unit scale
#'
#' @param x the double to be converted
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a unit scale
#' @export
#' @useDynLib zikaProj
toUnitScale <- function(x, min, max) {
    .Call('zikaProj_toUnitScale', PACKAGE = 'zikaProj', x, min, max)
}

#' Converts to linear scale
#'
#' @param x the double to be converted back to linear scale
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a linear scale
#' @export
#' @useDynLib zikaProj 
fromUnitScale <- function(x, min, max) {
    .Call('zikaProj_fromUnitScale', PACKAGE = 'zikaProj', x, min, max)
}

likelihood <- function(dat, alphas, mus, sds) {
    .Call('zikaProj_likelihood', PACKAGE = 'zikaProj', dat, alphas, mus, sds)
}

#' @export
#' @useDynLib zikaProj
calculate_alphas <- function(y, probMicro, sampFreq) {
    .Call('zikaProj_calculate_alphas', PACKAGE = 'zikaProj', y, probMicro, sampFreq)
}

proposal_function <- function(current, step) {
    .Call('zikaProj_proposal_function', PACKAGE = 'zikaProj', current, step)
}

scaletuning2 <- function(step, popt, pcur) {
    .Call('zikaProj_scaletuning2', PACKAGE = 'zikaProj', step, popt, pcur)
}

