# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converts to unit scale
#'
#' @param x the double to be converted
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a unit scale
#' @export
#' @useDynLib zikaProj
toUnitScale <- function(x, min, max) {
    .Call('zikaProj_toUnitScale', PACKAGE = 'zikaProj', x, min, max)
}

#' Converts to linear scale
#'
#' @param x the double to be converted back to linear scale
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a linear scale
#' @export
#' @useDynLib zikaProj 
fromUnitScale <- function(x, min, max) {
    .Call('zikaProj_fromUnitScale', PACKAGE = 'zikaProj', x, min, max)
}

#' Calculate gaussian mixture model likelihood
#'
#' Given a matrix of data points (columns represent individuals, rows represent sampling times), computes the log likelihood using the gaussian mixture model with known alphas, mus and sds.
#' @param dat the matrix of data
#' @param alphas matrix of of alphas. 2 columns (1 for both distributions) with number of rows matching number of rows in dat
#' @param mus vector of mus for the 2 distributions 
#' @param sds vector of sds for the 2 distributions
#' @return a single log likelihood
#' @export
#' @useDynLib zikaProj 
likelihood <- function(dat, alphas, mus, sds) {
    .Call('zikaProj_likelihood', PACKAGE = 'zikaProj', dat, alphas, mus, sds)
}

#' Calculate likelihood for threshold data
#'
#' Given a matrix of threshold data (ie. microcephaly or not) for different sampling times, gives a log likelihood with the given parameter values
#' @param dat the matrix of data. 2 columns for counts of positive and negative, and N rows for each sampling time
#' @param alphas matrix of of alphas. 2 columns (1 for both distributions) with number of rows matching number of rows in dat
#' @param mus vector of mus for the 2 distributions 
#' @param sds vector of sds for the 2 distributions
#' @param threshold the threshold value below which a data point is classified as having microcephaly
#' @return a single log likelihood
#' @export
#' @useDynLib zikaProj 
likelihood_threshold <- function(dat, alphas, mus, sds, threshold) {
    .Call('zikaProj_likelihood_threshold', PACKAGE = 'zikaProj', dat, alphas, mus, sds, threshold)
}

#' Converts to linear scale
#'
#' @param x the double to be converted back to linear scale
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a linear scale
#' @export
#' @useDynLib zikaProj 
calculate_alphas <- function(y, probMicro, sampFreq) {
    .Call('zikaProj_calculate_alphas', PACKAGE = 'zikaProj', y, probMicro, sampFreq)
}

scaletuning2 <- function(step, popt, pcur) {
    .Call('zikaProj_scaletuning2', PACKAGE = 'zikaProj', step, popt, pcur)
}

proposal_function <- function(current, lower, upper, step) {
    .Call('zikaProj_proposal_function', PACKAGE = 'zikaProj', current, lower, upper, step)
}

